services:
  gcalc-django:
    container_name: gcalc-django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    expose: # Expose a porta para outros serviços no Docker Compose, não para o host
      - "8000"