# Generated by Django 5.0.14 on 2025-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.IntegerField(blank=True, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPF'),
        ),
    ]
