# Generated by Django 5.0.14 on 2025-06-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_cnpj_alter_clientes_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
    ]
