# Generated by Django 5.0.6 on 2024-05-23 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Reclamada',
                'verbose_name_plural': 'Reclamadas',
            },
        ),
        migrations.CreateModel(
            name='Reclamantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Reclamante',
                'verbose_name_plural': 'Reclamantes',
            },
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=50, verbose_name='N.Processo')),
                ('dt_ajuizamento', models.DateField(verbose_name='D.Ajuizamento')),
                ('reclamada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.reclamadas', verbose_name='Reclamada')),
                ('reclamante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.reclamantes', verbose_name='Reclamante')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
