# Generated by Django 5.0.6 on 2024-05-31 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='dt_ult_atualizacao',
            field=models.DateField(verbose_name='Ultima Atualização', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processos',
            name='formato',
            field=models.CharField(default='', max_length=50, verbose_name='Formato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processos',
            name='n_processo',
            field=models.CharField(max_length=26, verbose_name='N.Processo'),
        ),
        migrations.CreateModel(
            name='Andamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato')),
                ('grau', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato')),
                ('dt_andamento', models.DateField(verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processos', verbose_name='Processos')),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
            },
        ),
    ]
