# Generated by Django 5.0.14 on 2025-06-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='dt_ajuizamento',
            field=models.DateField(blank=True, null=True, verbose_name='D.Ajuizamento'),
        ),
    ]
