# Generated by Django 5.0.6 on 2024-05-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processos_dt_ult_atualizacao_processos_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='dt_ult_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima Atualização'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato'),
        ),
    ]
