# Generated by Django 5.0.14 on 2025-06-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_alter_processos_dt_ajuizamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='reclamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.reclamadas', verbose_name='Reclamada'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='reclamante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.reclamantes', verbose_name='Reclamante'),
        ),
    ]
