# Generated by Django 5.0.6 on 2024-05-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_alter_processos_dt_ult_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='dt_ult_verificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima Verificação'),
        ),
    ]
