# Generated by Django 5.0.6 on 2024-05-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_processos_dt_ult_verificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentos',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Formato'),
        ),
    ]
