# Generated by Django 5.0.6 on 2024-05-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_andamentos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamentos',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='andamentos',
            name='grau',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau'),
        ),
    ]
