# Generated by Django 5.0.14 on 2025-07-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=26, verbose_name='N.Processo')),
                ('dt_ajuizamento', models.DateField(blank=True, null=True, verbose_name='D.Ajuizamento')),
                ('formato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato')),
                ('dt_ult_atualizacao', models.DateField(blank=True, null=True, verbose_name='Ultima Atualização')),
                ('dt_ult_verificacao', models.DateField(blank=True, null=True, verbose_name='Ultima Verificação')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='Reclamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Reclamada',
                'verbose_name_plural': 'Reclamadas',
            },
        ),
        migrations.CreateModel(
            name='Reclamantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Reclamante',
                'verbose_name_plural': 'Reclamantes',
            },
        ),
        migrations.CreateModel(
            name='Andamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formato')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
                ('grau', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau')),
                ('dt_andamento', models.DateField(verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processos', verbose_name='Processos')),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
            },
        ),
        migrations.AddField(
            model_name='processos',
            name='reclamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.reclamadas', verbose_name='Reclamada'),
        ),
        migrations.AddField(
            model_name='processos',
            name='reclamante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.reclamantes', verbose_name='Reclamante'),
        ),
    ]
