# Generated by Django 5.0.14 on 2025-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='n_processo',
            field=models.CharField(max_length=26, unique=True, verbose_name='N.Processo'),
        ),
    ]
