# Generated by Django 5.0.14 on 2025-07-06 19:44

import apps.servicos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(verbose_name='Tipo de Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('dt_cadastro', models.DateField(verbose_name='Cadastro')),
                ('dt_prazo', models.DateField(verbose_name='Prazo')),
                ('status', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=50, null=True, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculos.calculos', verbose_name='Cálculo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.processos', verbose_name='Processo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.servicos.models.usuario_deletado), to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='MeusServicos',
            fields=[
                ('servicos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.servicos')),
            ],
            options={
                'verbose_name': 'Meu Serviço',
                'verbose_name_plural': 'Meus Serviços',
            },
            bases=('servicos.servicos',),
        ),
    ]
