# Generated by Django 5.0.14 on 2025-07-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='valor',
        ),
        migrations.AlterField(
            model_name='servicos',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tiposervicos', verbose_name='Tipo de Serviço'),
        ),
    ]
