# Generated by Django 5.0.14 on 2025-10-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servicos_valor_alter_servicos_tipo_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cadastro', models.DateField(verbose_name='Cadastro')),
                ('dt_faturamento', models.DateField(verbose_name='Faturamento')),
                ('status', models.CharField(blank=True, choices=[('Em Analise', 'Em Analise'), ('Enviado', 'Enviado'), ('Faturado', 'Faturado')], null=True, verbose_name='Status')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('servicos', models.ManyToManyField(to='servicos.servicos')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
    ]
