# Generated by Django 5.0.14 on 2025-10-05 03:06

import apps.acesso.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_faturas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturas',
            name='dt_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='faturas',
            name='nota_fiscal',
            field=models.CharField(blank=True, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='faturas',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.acesso.models.usuario_deletado), to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='faturas',
            name='dt_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Cadastro'),
        ),
        migrations.AlterField(
            model_name='faturas',
            name='dt_faturamento',
            field=models.DateField(blank=True, null=True, verbose_name='Faturamento'),
        ),
        migrations.AlterField(
            model_name='faturas',
            name='status',
            field=models.CharField(blank=True, choices=[('Atrasado', 'Atrasado'), ('Em Analise', 'Em Analise'), ('Enviado', 'Enviado'), ('Faturado', 'Faturado'), ('Pago', 'Pago')], null=True, verbose_name='Status'),
        ),
    ]
