# Generated by Django 5.0.14 on 2025-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_faturas_dt_prazo_faturas_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='dt_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='conclusao'),
        ),
    ]
