# Generated by Django 5.0.14 on 2025-10-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='logo_icon',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='logo_text',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
