# Generated by Django 5.0.6 on 2024-05-23 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Nome')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('observacao', models.TextField(verbose_name='Observações')),
                ('calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculos.calculos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='processos.processos')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicos.tiposervico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
