# Generated by Django 5.0.14 on 2025-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoServico',
            new_name='TipoServicos',
        ),
        migrations.AlterField(
            model_name='servicos',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
