# Generated by Django 5.0.6 on 2024-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servicos_calculo_alter_servicos_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='dt_prazo',
            field=models.DateField(default=None, verbose_name='Prazo'),
            preserve_default=False,
        ),
    ]
