# Generated by Django 5.0.14 on 2025-06-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_tiposervico_tiposervicos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosColab',
            fields=[
                ('servicos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.servicos')),
            ],
            bases=('servicos.servicos',),
        ),
    ]
