# Generated by Django 5.0.6 on 2024-06-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servicos_dt_prazo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoServico',
            new_name='TipoServicos',
        ),
    ]
