# Generated by Django 5.0.14 on 2025-06-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servicoscolab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicosColab',
            new_name='MeusServicos',
        ),
        migrations.AlterModelOptions(
            name='meusservicos',
            options={'verbose_name': 'Meu Serviço', 'verbose_name_plural': 'Meus Serviços'},
        ),
    ]
