# Generated by Django 5.0.14 on 2025-06-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_cnpj_alter_clientes_cpf'),
        ('servicos', '0005_servicos_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicos',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
