# Generated by Django 5.0.14 on 2025-06-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_cnpj_alter_clientes_cpf'),
        ('servicos', '0006_tiposervicos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicos',
            name='cliente',
            field=models.CharField(choices=[('Alves e Castro', 'Alves e Castro')], verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='processo',
            field=models.CharField(choices=[('0321515-15.8616.5.16.5151', '0321515-15.8616.5.16.5151')], verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('pedro', 'pedro'), ('suporte', 'suporte')], null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='tipo_servico',
            field=models.CharField(choices=[('Liquidação', 'Liquidação')], verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='tiposervicos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes', verbose_name='Cliente'),
        ),
    ]
