# Generated by Django 5.0.14 on 2025-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_servicos_valor_alter_servicos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='tipo_servico',
            field=models.CharField(verbose_name='Tipo de Serviço'),
        ),
        migrations.DeleteModel(
            name='TipoServicos',
        ),
    ]
