# Generated by Django 5.0.14 on 2025-06-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_alter_servicos_tipo_servico_delete_tiposervicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='cliente',
            field=models.CharField(choices=[('Alves e Castro', 'Alves e Castro'), ('Adv Cardoso', 'Adv Cardoso')], verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='processo',
            field=models.CharField(choices=[('0321515-15.8616.5.16.5151', '0321515-15.8616.5.16.5151'), ('0020656-12.2018.5.04.0001', '0020656-12.2018.5.04.0001')], verbose_name='Processo'),
        ),
    ]
