# Generated by Django 5.0.14 on 2025-07-14 23:48

import apps.acesso.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calculos',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.acesso.models.usuario_deletado), to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
