# Generated by Django 5.0.14 on 2025-07-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_calculos_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculos',
            options={'permissions': [('view_meus_calculos', 'Can view Meus Cálculos'), ('add_meus_calculos', 'Can add Meus Cálculos'), ('change_meus_calculos', 'Can change Meus Cálculos'), ('delete_meus_calculos', 'can delete Meus Cálculos')], 'verbose_name': 'Cálculo', 'verbose_name_plural': 'Cálculos'},
        ),
    ]
