# Generated by Django 5.0.14 on 2025-07-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_alter_calculos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculos',
            options={'permissions': [('view_meus_calculos', 'Can view Meus Cálculos'), ('add_meus_calculos', 'Can add Meus Cálculos'), ('change_meus_calculos', 'Can change Meus Cálculos'), ('delete_meus_calculos', 'Can delete Meus Cálculos'), ('importar_calculos', 'Can import Cálculos')], 'verbose_name': 'Cálculo', 'verbose_name_plural': 'Cálculos'},
        ),
    ]
