# Generated by Django 5.0.6 on 2024-05-23 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio_calc', models.DateField(verbose_name='D.Inicio')),
                ('dt_fim_calc', models.DateField(verbose_name='D.Fim')),
                ('dt_liquidacao', models.DateField(verbose_name='D.Liquidação')),
                ('dt_criacao', models.DateField(auto_now=True, verbose_name='D.Criação')),
                ('n_arquivo', models.CharField(max_length=200, verbose_name='Nome do aquivo')),
                ('n_pje', models.IntegerField(verbose_name='N.Cálculo')),
                ('per_parcelas_rt', models.FloatField(verbose_name='% Parcelas Remuneratórias e Tributáveis')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processos', verbose_name='Nº Processo')),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
            },
        ),
        migrations.CreateModel(
            name='CredDesReclamante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.calculos', verbose_name='Cálculo')),
            ],
            options={
                'verbose_name': 'Crédito e Desconto de Reclamante',
                'verbose_name_plural': 'Créditos e Descontos de Reclamante',
            },
        ),
        migrations.CreateModel(
            name='DebitosReclamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.calculos', verbose_name='Cálculo')),
            ],
            options={
                'verbose_name': 'Debito',
                'verbose_name_plural': 'Debitos',
            },
        ),
        migrations.CreateModel(
            name='VerbasCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantidade', models.FloatField(blank=True, null=True, verbose_name='Valor Devido')),
                ('v_devido', models.FloatField(blank=True, null=True, verbose_name='Valor Devido')),
                ('v_pago', models.FloatField(blank=True, null=True, verbose_name='Valor Pago')),
                ('v_calculado', models.FloatField(blank=True, null=True, verbose_name='Valor Calculado')),
                ('v_corrigido', models.FloatField(verbose_name='Valor Corrigido')),
                ('juros', models.FloatField(verbose_name='Juros')),
                ('total', models.FloatField(verbose_name='Total')),
                ('comentario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentário')),
                ('insidencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Incidência(s)')),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.calculos', verbose_name='Cálculo')),
            ],
            options={
                'verbose_name': 'Verba',
                'verbose_name_plural': 'Verbas',
            },
        ),
        migrations.CreateModel(
            name='VerbasCalcDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Período Mensal')),
                ('base', models.FloatField(blank=True, null=True, verbose_name='Base')),
                ('divisor', models.FloatField(blank=True, null=True, verbose_name='Divisor')),
                ('multiplicador', models.FloatField(blank=True, null=True, verbose_name='Multiplicador')),
                ('quantidade', models.FloatField(blank=True, null=True, verbose_name='Quantidade')),
                ('dobra', models.BooleanField(default=False, verbose_name='Dobra')),
                ('devido', models.FloatField(verbose_name='Devido')),
                ('pago', models.FloatField(verbose_name='Pago')),
                ('diferenca', models.FloatField(verbose_name='Diferença')),
                ('icm', models.FloatField(verbose_name='Índice Correção')),
                ('v_corrigido', models.FloatField(verbose_name='Valor Corrigido')),
                ('verba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.verbascalc', verbose_name='Verba')),
            ],
            options={
                'verbose_name': 'Detalhe de Verba',
                'verbose_name_plural': 'Detalhes de Verbas',
            },
        ),
    ]
