# Generated by Django 5.0.6 on 2024-05-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbascalc',
            name='quantidade',
        ),
    ]
